services:
    db:
        image: mysql:8.0
        restart: always
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app_network

    backend:
        build: .
        container_name: backend
        volumes:
            - .:/backend
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            - MYSQL_HOST=db
            - MYSQL_PORT=3306
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - FLASK_ENV=${FLASK_ENV}
            - PYTHONUNBUFFERED=1
        restart: unless-stopped
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    mysql_data:
